version: '3.8'

services:
  db:
    image: mysql:9.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: banco_de_dados_trafego
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - rede-app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: senha
      DB_NAME: banco_de_dados_trafego
      INTERFACE: ${INTERFACE}
      TIMEOUT: ${TIMEOUT}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - rede-app
    links:
      - db

networks:
  rede-app:
    driver: bridge